language: node_js
node_js:
  - "11"
after_script:
  - npm run build-linux
  - cp ${TRAVIS_BUILD_DIR}/node_modules/sleep/build/Release/node_sleep.node node_sleep.node
  - rm .gitignore
  - rm .travis.yml
  - rm index.html
  - rm index.js
  - rm index.min.html
  - rm logo.png
  - rm package-lock.json
  - rm package.json
  - rm README.md
  - rm -rf static
  - rm -rf node_modules
  - rm -rf docs/cues
  - rm -rf docs/fixtures
  - rm -rf docs/groups
  - rm -rf docs/images
  - rm docs/book.json
  - rm docs/README.md
  - rm docs/SUMMARY.md
  - rm docs/supported_hardware.md
  - rm docs/supported_software.md
  - rm docs/website.css
  - zip ${TRAVIS_BUILD_DIR}/tonalite.zip ${TRAVIS_BUILD_DIR}
