language: node_js
node_js:
  - "11"
after_script:
  - sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
  - npm install -g gitbook-cli
  - cd docs && gitbook install && cd ../
  - npm run build-docs
  - npm run build-docs-pdf
  - npm run build-linux
  - cp node_modules/sleep/build/Release/node_sleep.node node_sleep.node
  - cp docs/documentation.pdf documentation.pdf
  - rm .gitignore
  - rm .travis.yml
  - rm index.html
  - rm index.js
  - rm index.min.html
  - rm presets.html
  - rm presets.min.html
  - rm open-source-licenses.txt
  - rm logo.png
  - rm package-lock.json
  - rm package.json
  - rm README.md
  - rm -rf static
  - rm -rf node_modules
  - rm -rf docs/cues
  - rm -rf docs/fixtures
  - rm -rf docs/groups
  - rm -rf docs/images
  - rm -rf docs/dist
  - rm -rf docs
  - zip -9 ${TRAVIS_BUILD_DIR}/tonalite-linux.zip ${TRAVIS_BUILD_DIR} -r
