language: python
python:
  - "3.6"
os:
  - linux
  - osx
install:
  - pip install python-socketio aiohttp PyInstaller passlib cython socketIO-client
script:
  - cd src_channelman
  - python setup.py build_ext --inplace
  - ls
  - cd ../
