image: Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
artifacts:
  - path: Tonalite-$(appveyor_build_version)-Win64.zip
    name: Tonalite-$(appveyor_build_version)-Win64
  - path: docs/Tonalite-v1.0.0-Documentation.pdf
    name: Tonalite-v1.0.0-Documentation-$(appveyor_build_version).pdf
install:
  - "%PYTHON%\\python.exe -m pip install python-socketio aiohttp PyInstaller passlib cython socketIO-client"
test_script:
  - "%PYTHON%\\python.exe tests.py"
build_script:
  - "cd src_channelman && %PYTHON%\\python.exe setup.py build_ext --inplace && copy channelman.cp36-win_amd64.pyd ..\\channelman.pyd && cd ../"
  - "%PYTHON%\\python.exe -m PyInstaller tonalite-win.spec"
  - "rmdir %APPVEYOR_BUILD_FOLDER%\\dist\\tonalite\\static\\sass /s /Q"
  - "7z a Tonalite-%APPVEYOR_BUILD_VERSION%-Win64.zip %APPVEYOR_BUILD_FOLDER%\\dist\\tonalite\\*"
  
