image: Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
artifacts:
  - path: Tonalite-$(appveyor_build_version).zip
    name: Tonalite-$(appveyor_build_version)
install:
  - "%PYTHON%\\python.exe -m pip install python-socketio aiohttp PyInstaller passlib cython"
test_script:
  - "%PYTHON%\\python.exe tests.py"
build_script:
  - "cd src_channelman && %PYTHON%\\python.exe setup.py build_ext --inplace && copy channelman.cp36-win_amd64.pyd ..\\channelman.pyd && cd ../"
  - "%PYTHON%\\python.exe -m PyInstaller tonalite.spec"
  - "7z a Tonalite-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\\dist\\tonalite\\*"
  
