image: Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
install:
  - "%PYTHON%\\python.exe -m pip install python-socketio aiohttp PyInstaller passlib cython"
build: off
test_script:
  - "cd src_channelman && %PYTHON%\\python.exe setup.py build_ext --inplace && copy channelman.cp36-win_amd64.pyd ..\\channelman.pyd && cd ../"
  - "%PYTHON%\\python.exe tests.py"
on_success:
  - "%PYTHON%\\python.exe -m PyInstaller tonalite.spec"